### ISSUE TITLE
`.first` throws an error if used with less than 2 values

### ISSUE THREAD

**Issue by renatoargh** [humanwhocodes/env#26]
I have a dinamically set array of env variables which I pass to `.first`. Having this limitation makes me check for the length of the array and use `.get` if there is only a single element.

What is the reason behind this limitation? Is it something that we stop throwing this error, or at least make it configurable?

PS.: thanks for your awesome lib 👍

**Comment by nzakas** [comment]
Ah, that's an interesting use case I didn't consider. Yes, the idea was that if you were using `first()` with a single-item array, that it was probably an error and you should be alerted.

I can see an argument this case isn't important enough to throw an error because there is really no harm done with a one-item array. I'm not opposed to changing this behavior.

**Comment by renatoargh** [comment]
If it is fine for you then I will try to come up with a PR soon (not sure when though). In the meanwhile I will keep my `if`s :)

**Comment by nzakas** [comment]
I'm on it. 👍
